apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: codisclusters.codis.k8s.io
spec:
  group: codis.k8s.io
  names:
    kind: CodisCluster
    plural: codisclusters
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            codisDashboard:
              properties:
                productAuth:
                  type: string
                replicas:
                  format: int32
                  type: integer
              required:
              - replicas
              - productAuth
              type: object
            codisFe:
              properties:
                replicas:
                  format: int32
                  type: integer
              required:
              - replicas
              type: object
            codisProxy:
              properties:
                hpaSpec:
                  properties:
                    cpuUsedThreshold:
                      format: int32
                      type: integer
                    maxReplicas:
                      format: int32
                      type: integer
                    minReplicas:
                      format: int32
                      type: integer
                  required:
                  - minReplicas
                  - maxReplicas
                  - cpuUsedThreshold
                  type: object
                replicas:
                  format: int32
                  type: integer
                sessionAuth:
                  type: string
              required:
              - replicas
              - sessionAuth
              type: object
            codisServer:
              properties:
                groupReplicas:
                  format: int32
                  type: integer
                replicas:
                  format: int32
                  type: integer
              required:
              - replicas
              - groupReplicas
              type: object
            coordinatorAddr:
              type: string
            coordinatorName:
              type: string
            schedulerName:
              type: string
            sentinel:
              properties:
                replicas:
                  format: int32
                  type: integer
              required:
              - replicas
              type: object
          required:
          - coordinatorName
          - coordinatorAddr
          type: object
        status:
          properties:
            codisDashboard:
              properties:
                phase:
                  type: string
                statefulSet:
                  type: object
              type: object
            codisFeStatus:
              properties:
                deployment:
                  type: object
                phase:
                  type: string
              type: object
            codisProxy:
              properties:
                deployment:
                  type: object
                phase:
                  type: string
              type: object
            codisServer:
              properties:
                phase:
                  type: string
                statefulSet:
                  type: object
              type: object
            sentinelStatus:
              properties:
                phase:
                  type: string
                statefulSet:
                  type: object
              type: object
          type: object
      required:
      - spec
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - codis.k8s.io
  resources:
  - codisclusters
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: system
---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-server-secret
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  name: controller-manager-service
  namespace: default
spec:
  ports:
  - port: 443
  selector:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  name: controller-manager
  namespace: default
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      controller-tools.k8s.io: "1.0"
  serviceName: controller-manager-service
  template:
    metadata:
      labels:
        control-plane: controller-manager
        controller-tools.k8s.io: "1.0"
    spec:
      containers:
      - command:
        - /root/manager
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SECRET_NAME
          value: webhook-server-secret
        image: ccr.ccs.tencentyun.com/codis/codis-operator:latest
        imagePullPolicy: Always
        name: manager
        ports:
        - containerPort: 9876
          name: webhook-server
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
        - mountPath: /tmp/cert
          name: cert
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-secret
