apiVersion: codis.k8s.io/v1alpha1
kind: CodisCluster
metadata:
  labels:
    app: codis-cluster
  name: codis-test 
spec:
  coordinatorName: etcd
  coordinatorAddr: YOUR_ETCD_SERVICE_IP:2379
  codisProxy:
    replicas: 3
    image: ccr.ccs.tencentyun.com/codis/codis3.2:latest
    sessionAuth: session
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 100Mi
    hpaSpec:
      minReplicas: 2
      maxReplicas: 20
      cpuUsedThreshold: 60
  codisServer:
    replicas: 4
    groupReplicas: 2
    image: ccr.ccs.tencentyun.com/codis/codis3.2:latest
  codisDashboard:
    replicas: 1
    image: ccr.ccs.tencentyun.com/codis/codis3.2:latest
    productAuth: product
  codisFe:
    replicas: 2
    image: ccr.ccs.tencentyun.com/codis/codis3.2:latest
  sentinel:
    replicas: 5
    image: ccr.ccs.tencentyun.com/codis/codis3.2:latest
